# Generated by Django 6.0.5 on 2026-05-23 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CareerDirection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="方向名称")),
                ("match_score", models.FloatField(default=0, verbose_name="匹配度")),
                (
                    "market_demand",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="市场需求"
                    ),
                ),
                (
                    "typical_positions",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="典型岗位"
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="推荐理由")),
                (
                    "is_excluded",
                    models.BooleanField(default=False, verbose_name="是否排除"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="career_directions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "就业方向",
                "verbose_name_plural": "就业方向",
                "db_table": "career_directions",
                "ordering": ["-match_score"],
            },
        ),
        migrations.CreateModel(
            name="CareerPlanReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "overall_score",
                    models.FloatField(default=0, verbose_name="综合评分"),
                ),
                ("summary", models.TextField(blank=True, verbose_name="分析摘要")),
                (
                    "short_term",
                    models.TextField(blank=True, verbose_name="短期规划 (0-6月)"),
                ),
                (
                    "mid_term",
                    models.TextField(blank=True, verbose_name="中期规划 (6月-2年)"),
                ),
                (
                    "long_term",
                    models.TextField(blank=True, verbose_name="长期规划 (2-5年)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="career_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "职业规划报告",
                "verbose_name_plural": "职业规划报告",
                "db_table": "career_plan_reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImprovementSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "skill_name",
                    models.CharField(max_length=100, verbose_name="技能名称"),
                ),
                (
                    "current_score",
                    models.FloatField(default=0, verbose_name="当前分数"),
                ),
                ("target_score", models.FloatField(default=0, verbose_name="目标分数")),
                (
                    "learning_path",
                    models.TextField(blank=True, verbose_name="学习路径"),
                ),
                (
                    "recommended_courses",
                    models.TextField(blank=True, verbose_name="推荐课程"),
                ),
                (
                    "recommended_books",
                    models.TextField(blank=True, verbose_name="推荐书籍"),
                ),
                (
                    "recommended_projects",
                    models.TextField(blank=True, verbose_name="推荐项目"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="improvements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "提升建议",
                "verbose_name_plural": "提升建议",
                "db_table": "improvement_suggestions",
                "ordering": ["-current_score"],
            },
        ),
        migrations.CreateModel(
            name="JobRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "overall_match",
                    models.FloatField(default=0, verbose_name="综合匹配度"),
                ),
                ("major_match", models.FloatField(default=0, verbose_name="专业匹配")),
                ("skill_match", models.FloatField(default=0, verbose_name="能力匹配")),
                (
                    "interest_match",
                    models.FloatField(default=0, verbose_name="兴趣匹配"),
                ),
                ("salary_match", models.FloatField(default=0, verbose_name="薪资匹配")),
                ("city_match", models.FloatField(default=0, verbose_name="城市匹配")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="jobs.jobposting",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "岗位推荐",
                "verbose_name_plural": "岗位推荐",
                "db_table": "job_recommendations",
                "ordering": ["-overall_match"],
            },
        ),
        migrations.CreateModel(
            name="MockInterviewRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_job",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="目标岗位"
                    ),
                ),
                (
                    "interview_type",
                    models.CharField(
                        choices=[
                            ("behavioral", "行为面试"),
                            ("technical", "技术面试"),
                            ("comprehensive", "综合面试"),
                        ],
                        max_length=20,
                        verbose_name="面试类型",
                    ),
                ),
                ("rounds", models.IntegerField(default=3, verbose_name="轮数")),
                (
                    "overall_score",
                    models.FloatField(default=0, verbose_name="综合评分"),
                ),
                ("feedback", models.TextField(blank=True, verbose_name="评估反馈")),
                (
                    "status",
                    models.CharField(
                        default="pending", max_length=20, verbose_name="状态"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "模拟面试",
                "verbose_name_plural": "模拟面试",
                "db_table": "mock_interview_records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InterviewMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("ai", "AI 面试官"), ("user", "用户")],
                        max_length=10,
                        verbose_name="角色",
                    ),
                ),
                ("content", models.TextField(verbose_name="内容")),
                ("feedback", models.TextField(blank=True, verbose_name="反馈")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "interview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="career.mockinterviewrecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "面试消息",
                "verbose_name_plural": "面试消息",
                "db_table": "interview_messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResumeOptimizationReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_job",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="目标岗位"
                    ),
                ),
                (
                    "original_resume",
                    models.TextField(blank=True, verbose_name="原始简历内容"),
                ),
                (
                    "optimized_resume",
                    models.TextField(blank=True, verbose_name="优化后简历"),
                ),
                ("suggestions", models.TextField(blank=True, verbose_name="优化建议")),
                (
                    "overall_score",
                    models.FloatField(default=0, verbose_name="综合评分"),
                ),
                (
                    "keyword_coverage",
                    models.FloatField(default=0, verbose_name="关键词覆盖度"),
                ),
                (
                    "status",
                    models.CharField(
                        default="pending", max_length=20, verbose_name="状态"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resume_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "简历优化报告",
                "verbose_name_plural": "简历优化报告",
                "db_table": "resume_optimization_reports",
                "ordering": ["-created_at"],
            },
        ),
    ]
