# Generated by Django 6.0.5 on 2026-05-23 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobPosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="岗位名称")),
                ("company", models.CharField(max_length=200, verbose_name="公司名称")),
                ("city", models.CharField(max_length=50, verbose_name="城市")),
                ("salary_min", models.IntegerField(verbose_name="最低薪资(K)")),
                ("salary_max", models.IntegerField(verbose_name="最高薪资(K)")),
                ("job_type", models.CharField(max_length=50, verbose_name="岗位类型")),
                (
                    "experience",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="经验要求"
                    ),
                ),
                (
                    "education",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="学历要求"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="岗位描述")),
                ("requirements", models.TextField(blank=True, verbose_name="任职要求")),
                (
                    "tags",
                    models.CharField(blank=True, max_length=500, verbose_name="标签"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否在招"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "岗位信息",
                "verbose_name_plural": "岗位信息",
                "db_table": "job_postings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="收藏时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="jobs.jobposting",
                    ),
                ),
            ],
            options={
                "verbose_name": "岗位收藏",
                "verbose_name_plural": "岗位收藏",
                "db_table": "job_favorites",
                "unique_together": {("user", "job")},
            },
        ),
    ]
