# Generated by Django 6.0.5 on 2026-05-23 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompetencyResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "learning_score",
                    models.FloatField(default=0, verbose_name="学习能力"),
                ),
                (
                    "communication_score",
                    models.FloatField(default=0, verbose_name="沟通能力"),
                ),
                (
                    "teamwork_score",
                    models.FloatField(default=0, verbose_name="团队协作"),
                ),
                (
                    "problem_solving_score",
                    models.FloatField(default=0, verbose_name="问题解决"),
                ),
                (
                    "leadership_score",
                    models.FloatField(default=0, verbose_name="领导力"),
                ),
                (
                    "innovation_score",
                    models.FloatField(default=0, verbose_name="创新能力"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competency",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "胜任力结果",
                "verbose_name_plural": "胜任力结果",
                "db_table": "competency_results",
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("internship", "实习经历"),
                            ("project", "项目经历"),
                            ("competition", "竞赛经历"),
                            ("activity", "活动经历"),
                        ],
                        max_length=20,
                        verbose_name="类型",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                (
                    "organization",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="组织/公司"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="开始日期")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="结束日期"),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "经历",
                "verbose_name_plural": "经历",
                "db_table": "experiences",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="HollandResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, verbose_name="霍兰德代码")),
                ("r_score", models.FloatField(default=0, verbose_name="现实型")),
                ("i_score", models.FloatField(default=0, verbose_name="研究型")),
                ("a_score", models.FloatField(default=0, verbose_name="艺术型")),
                ("s_score", models.FloatField(default=0, verbose_name="社会型")),
                ("e_score", models.FloatField(default=0, verbose_name="企业型")),
                ("c_score", models.FloatField(default=0, verbose_name="常规型")),
                ("description", models.TextField(blank=True, verbose_name="结果描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holland",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "霍兰德结果",
                "verbose_name_plural": "霍兰德结果",
                "db_table": "holland_results",
            },
        ),
        migrations.CreateModel(
            name="MBTIResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, verbose_name="MBTI 类型")),
                (
                    "ei_score",
                    models.FloatField(default=50, verbose_name="外向-内向分数"),
                ),
                (
                    "sn_score",
                    models.FloatField(default=50, verbose_name="感觉-直觉分数"),
                ),
                (
                    "tf_score",
                    models.FloatField(default=50, verbose_name="思维-情感分数"),
                ),
                (
                    "jp_score",
                    models.FloatField(default=50, verbose_name="判断-知觉分数"),
                ),
                ("description", models.TextField(blank=True, verbose_name="类型描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mbti",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "MBTI 结果",
                "verbose_name_plural": "MBTI 结果",
                "db_table": "mbti_results",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="", max_length=50, verbose_name="姓名"),
                ),
                (
                    "gender",
                    models.CharField(blank=True, max_length=10, verbose_name="性别"),
                ),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="出生日期"),
                ),
                (
                    "university",
                    models.CharField(blank=True, max_length=100, verbose_name="学校"),
                ),
                (
                    "major",
                    models.CharField(blank=True, max_length=100, verbose_name="专业"),
                ),
                (
                    "grade",
                    models.CharField(blank=True, max_length=20, verbose_name="年级"),
                ),
                ("gpa", models.FloatField(blank=True, null=True, verbose_name="GPA")),
                ("introduction", models.TextField(blank=True, verbose_name="自我介绍")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "用户档案",
                "verbose_name_plural": "用户档案",
                "db_table": "user_profiles",
            },
        ),
    ]
